/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Dec 27, 2011, 1:38:24 AM
 */
package javamove;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.geom.Arc2D;
import java.awt.geom.RoundRectangle2D;
import java.awt.geom.RoundRectangle2D.Double;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JPanel;

/**
 *
 * @author jianhuashao
 */
public class MainFrame extends javax.swing.JFrame implements Runnable{
    
    MyPanel panel = new MyPanel();
    Thread mythread = new Thread();
    int state = 0;
    int state_yunsu = 1;
    
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        this.mypanel.setLayout(new BoxLayout(this.mypanel, BoxLayout.PAGE_AXIS));
        panel.setVisible(true);
        this.mypanel.add(panel);
        panel.setSize(this.mypanel.getWidth(), this.mypanel.getHeight());
        this.mypanel.add(panel, BorderLayout.CENTER);
        System.out.println("init finished");
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mypanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mypanel.setBorder(javax.swing.BorderFactory.createTitledBorder("MyPanel"));

        org.jdesktop.layout.GroupLayout mypanelLayout = new org.jdesktop.layout.GroupLayout(mypanel);
        mypanel.setLayout(mypanelLayout);
        mypanelLayout.setHorizontalGroup(
            mypanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 406, Short.MAX_VALUE)
        );
        mypanelLayout.setVerticalGroup(
            mypanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 248, Short.MAX_VALUE)
        );

        jButton1.setText("匀速");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("圆周");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("抛体");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("弹射");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButton4)
                .add(96, 96, 96))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mypanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2)
                    .add(jButton3)
                    .add(jButton4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(mypanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //System.out.println(evt.toString());
        this.state = this.state_yunsu;
        mythread = new Thread(this);
        mythread.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //System.out.println(evt.toString());
        int y = this.mypanel.getHeight();
        int x = this.mypanel.getWidth();
        System.out.println(y+":"+x);
        panel.changexy(20, 20);
        System.out.println(panel.y+":"+panel.x);
        panel.repaint();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //System.out.println(evt.toString());
        if (mythread.isAlive()){
            mythread.interrupt();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //System.out.println(evt.toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel mypanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        //throw new UnsupportedOperationException("Not supported yet.");
        System.out.println("this.state:"+this.state);
        if (this.state == this.state_yunsu){
            float x = this.panel.myx();
            float y = this.panel.myy();
            float t = 5;
            float speed = 5;
            float x_final = this.panel.getWidth() - x;
            float y_final = this.panel.getHeight();
            //float x_final = this.mypanel.getHeight() - x;
            //float y_final = this.mypanel.getHeight();
            float x_n = x_final-x;
            float y_n = y;
            float x_speed = x_n / t;
            float y_speed = 0;
            float x_t = x;
            float y_t = y;
            System.out.println("speed: x="+x_speed+", y="+y_speed);
            boolean nostop = true;
            while (nostop) {
                System.out.println(x_t +":"+ x_final);
                if (x_t < x_final){
                    try {
                        Thread.sleep(5);
                        x_t = (float) (x_t+speed*5*0.01);
                        y_t = y_t;
                        this.panel.changexy(x_t, y_t);
                        this.panel.repaint();
                        //System.out.println(x_t+":"+y_t);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    nostop = false;
                }
            }
                 
            
        }
        this.state = 0;
        System.out.println("run down");
    }
}
